CREATE TABLE PERSON (
                        ID  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
                        NAME VARCHAR2(40) NOT NULL,
                        LOGIN VARCHAR2(30) NOT NULL,
                        PASSWORD VARCHAR(30) NOT NULL,
                        EMAIL VARCHAR(20) NOT NULL,
                        ROLE NUMBER NOT NULL,
                        SOCIAL_STATUS NUMBER NOT NULL,
                        CONSTRAINT PERSON_PK PRIMARY KEY (ID)
)

CREATE SEQUENCE SQ_PERSON START WITH 1 INCREMENT BY 1;
INSERT INTO PERSON VALUES (SQ_PERSON.nextval, 'Chary', 'Mess', '112 Yellow Hill', 'LOLKEK', 1, 2);